POST http://localhost:3003/api/blogs
content-type: application/json 

{
    "title": "Bob's Blog",
    "author": "Bob Smith",
    "url": "https://example.com",
    "likes": 10
}

###
POST http://localhost:3003/api/blogs
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impqb24iLCJpZCI6IjY0YWRlMDk2NTBlOTM0NGUyNTQxNjUzZCIsImlhdCI6MTY4OTEzNTA5NywiZXhwIjoxNjg5MTM4Njk3fQ.MPYo9I837B_dvnepSjsZykJ-bkB8kg-xXyijjMD4kQ4

{
    "title": "It's a Me",
    "author": "Mario",
    "url": "https://example.com",
    "likes": 10
}
